# Libreria numpy
Numpy es una libreria que contiene funciones utiles del algebra lineal, aritmetica y administración de datos la cual es muy util, para empezar a usarla se tiene que realizar una acción que se llama importar, cual se realiza con el siguiente código 
```
import numpy as np
```
el ``as np`` es una abreviación usual en la libreria numpy, este puede ser cualquier nombre pero por estandar se usa np.

In [1]:
import numpy as np

Anteriormente se había dicho como crear listas de valores en python, lo cual se realiza de la siguiente manera:
```
list=[1,2,3,4,5]
```
en numpy, esta misma acción tendria que realizarse de la siguiente manera
```
list=np.array([1,2,3,4,5])
```
A simple vista lo único que hace es aumentar las lineas que escribimos, pero esto dota de más acciones a las variables que podemos usar.

In [5]:
"""
En estas lineas de código se puede apreciar que la clase de la variable cambia
si la realizó como una lista o como un array de numpy.
"""
list=[1,2,3,4,5]
print(type(list))
list=np.array([1,2,3,4,5])
print(type(list))

<class 'list'>
<class 'numpy.ndarray'>


Para obersvar el beneficio que nos da numpy, realizaremos la siguiente operación, multiplicación de matrices. Nosotros sabemos que este es un proceso tedioso y largo, por lo tanto algunas veces complicado de programar, intentaremos recrear la siguiente multiplicación:


\begin{equation}
\left[ \begin{matrix} 
3 & 5 \\
4 & 6 
\end{matrix} \right]
\left[ \begin{matrix} 
8 & 3 \\
4 & 9 
\end{matrix} \right] = 
\left[ \begin{matrix} 
44 & 54 \\
56 & 66
\end{matrix} \right]
\end{equation}
que escribiendo esta operación reducida es la siguiente
\begin{equation}
C_{ij}=A_{ik}B_{kj}
\end{equation}

In [19]:
matriz_a=[[3,5],
          [4,6]]
matriz_b=[[8,3],
          [4,9]]
# Se inicio la matriz de resultado para tener la forma 
matriz_result=[[0,0],
               [0,0]]
for i in range(2):
    for j in range(2):
        sum=0
        for k in range(2):
            sum+=matriz_a[i][k]*matriz_b[k][j]
        matriz_result[i][j]=sum
# Lo siguiente no es necesario, es solo para que se vea bonito
for values in matriz_result:
    print("|{} {}|".format(values[0],values[1]))
            

|44 54|
|56 66|


Si vemos, el algoritmo para realizar la multiplicación no es tan sencillo, esta operación ya la tiene definida, y no es necesario escribirla nosotros mismos, su uso se puede hacer como en la siguiente celda:

In [25]:
matriz_a=np.array([[3,5],
                   [4,6]])
matriz_b=np.array([[8,3],
                   [4,9]])
"""
Forma 1
"""
matriz_result=matriz_a.dot(matriz_b)
print("Resultado de la forma 1")
print(matriz_result)
"""
Forma 2
"""
matriz_result=np.dot(matriz_a,matriz_b)
print("Resultado de la forma 2")
print(matriz_result)

Resultado de la forma 1
[[44 54]
 [56 66]]
Resultado de la forma 2
[[44 54]
 [56 66]]


Con esto, nos damos cuenta que es lo mismo, y nos podemos ahorrar trabajo de calculo o de escritura, por lo que nos ayuda mucho. Esta función no es la única que contiene la libreria numpy, esta contiene más y en seguida mostraremos algunas de las más usuales.

# Calculo de las medidas centrales
##### Mediana
`` np.median(data)``
##### media (promedio)
`` np.mean(data)``
##### desviación estandar
`` np.std(data)``

In [45]:
def write(text,value):
    print("\nEsta es {} que tiene un valor de {:.2f}".format(text,value))
    
data=np.array([1456,1,12,16,1,14,32,1,1])
# Mediana
median=np.median(data)
# Media (promedio)
mean=np.mean(data)
# Desviación estandar
std=np.std(data)
write("la mediana",median)
write("el promedio",mean)
write("la desviación estandar",std)


Esta es la mediana que tiene un valor de 12.00

Esta es el promedio que tiene un valor de 170.44

Esta es la desviación estandar que tiene un valor de 454.62


# Creación de matrices o vectores


In [65]:
"""
Creación de matrices y vectores con valores de: 0
                                                1
                                                aleatorios
"""
# Matriz con ceros
matriz_zeros=np.zeros((5,5))
print("\nMatriz de ceros")
print(matriz_zeros)
# Matriz con unos
matriz_ones=np.ones((10,10))
print("\nMatriz de unos")
print(matriz_ones)
# Matriz con valores aleatorios
matriz_random=np.random.random((3,3))
print("\nMatriz de números aleatorios")
print(matriz_random)


Matriz de ceros
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Matriz de unos
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Matriz de números aleatorios
[[0.67831325 0.12951749 0.36998261]
 [0.05469209 0.67353724 0.41681435]
 [0.58439294 0.48808607 0.27348   ]]


# Algebra lineal

In [66]:
"""
Calculo de: Matriz inversa
            Determinante
            Eigenvectores y eigenfunciones
"""
# Matriz inversa
matriz_prueba=np.array([[4,6],
                        [-5,-2]])
inversa=np.linalg.inv(matriz_prueba)
print("\nMatriz inversa de la matriz de prueba")
print(inversa)

# Determinante de una matriz
det=np.linalg.det(matriz_prueba)
print("\nDeterminante de la matriz de prueba")
print(det)

# Eigenvalores y eigenvectores de una matriz
eigenvalues,eigenvectors=np.linalg.eig(matriz_prueba)
print("\nEigenvalores de la matriz de prueba")
print(eigenvalues)
print("\nEigenvectores de la matriz de prueba")
print(eigenvectors)



Matriz inversa de la matriz de prueba
[[-0.09090909 -0.27272727]
 [ 0.22727273  0.18181818]]

Determinante de la matriz de prueba
22.000000000000004

Eigenvalores de la matriz de prueba
[1.+4.58257569j 1.-4.58257569j]

Eigenvectores de la matriz de prueba
[[ 0.73854895+0.j          0.73854895-0.j        ]
 [-0.36927447+0.56407607j -0.36927447-0.56407607j]]


# Lectura de un archivo txt
Nota: Si se usa Google Colab, se tiene que subir el archivo a Google Drive
```
np.loadtxt(nombre del archivo, mas parametros)
```

In [49]:
folder="Datos/"
filename="datos.txt"
# Lecuta de datos
dates,ozone_list,years,months,days=np.loadtxt(folder+filename,unpack=True)
for date,ozone,year,month,day in zip(dates,ozone_list,years,months,days):
    print(date,ozone,year,month,day)

150111.0 274.0 2015.0 1.0 11.0
150112.0 255.023 2015.0 1.0 12.0
150117.0 255.023 2015.0 1.0 17.0
150120.0 256.489 2015.0 1.0 20.0
150127.0 267.267 2015.0 1.0 27.0
150129.0 262.889 2015.0 1.0 29.0
150204.0 259.424 2015.0 2.0 4.0
150207.0 301.867 2015.0 2.0 7.0
150208.0 259.424 2015.0 2.0 8.0
150209.0 279.533 2015.0 2.0 9.0
150210.0 282.378 2015.0 2.0 10.0
150211.0 259.424 2015.0 2.0 11.0
150218.0 259.424 2015.0 2.0 18.0
150219.0 290.767 2015.0 2.0 19.0
150220.0 259.424 2015.0 2.0 20.0
150225.0 281.067 2015.0 2.0 25.0
150226.0 297.322 2015.0 2.0 26.0
150303.0 273.379 2015.0 3.0 3.0
150312.0 273.379 2015.0 3.0 12.0
150322.0 282.4 2015.0 3.0 22.0
150323.0 289.411 2015.0 3.0 23.0
150324.0 277.844 2015.0 3.0 24.0
150327.0 318.1 2015.0 3.0 27.0
150328.0 301.178 2015.0 3.0 28.0
150329.0 287.6 2015.0 3.0 29.0
150330.0 278.733 2015.0 3.0 30.0
150402.0 293.0 2015.0 4.0 2.0
150423.0 275.933 2015.0 4.0 23.0
150426.0 282.089 2015.0 4.0 26.0
150428.0 311.8 2015.0 4.0 28.0
150429.0 306.25 2015.0 4.0 2

180516.0 287.812 2018.0 5.0 16.0
180517.0 279.633 2018.0 5.0 17.0
180518.0 292.011 2018.0 5.0 18.0
180525.0 282.011 2018.0 5.0 25.0
180526.0 288.833 2018.0 5.0 26.0
180527.0 279.511 2018.0 5.0 27.0
180528.0 295.167 2018.0 5.0 28.0
180529.0 279.433 2018.0 5.0 29.0
180530.0 287.812 2018.0 5.0 30.0
180531.0 277.1 2018.0 5.0 31.0
180602.0 291.667 2018.0 6.0 2.0
180604.0 281.411 2018.0 6.0 4.0
180605.0 291.533 2018.0 6.0 5.0
180606.0 283.44 2018.0 6.0 6.0
180607.0 289.933 2018.0 6.0 7.0
180623.0 282.667 2018.0 6.0 23.0
180628.0 296.789 2018.0 6.0 28.0
180629.0 318.433 2018.0 6.0 29.0
180701.0 287.236 2018.0 7.0 1.0
180711.0 288.089 2018.0 7.0 11.0
180712.0 295.567 2018.0 7.0 12.0
180715.0 306.733 2018.0 7.0 15.0
180716.0 304.144 2018.0 7.0 16.0
180717.0 287.236 2018.0 7.0 17.0
180718.0 290.967 2018.0 7.0 18.0
180719.0 287.236 2018.0 7.0 19.0
180720.0 291.4 2018.0 7.0 20.0
180721.0 292.911 2018.0 7.0 21.0
180722.0 297.656 2018.0 7.0 22.0
180723.0 290.344 2018.0 7.0 23.0
180728.0 288.222 2018

# Lectura de un archivo csv
Por defecto, numpy no tiene una función para leer csv, pero usando un parámetro de la funcion np.loadtxt, esta se puede usar.
```
np.loadtxt(nombre del archivo, delimiter="," ,mas parametros)
```

In [60]:
filename="Ozono_OMI.csv"
data_list=np.loadtxt(folder+filename,delimiter=",",usecols=np.arange(1,17))
print(data_list)

[[2005.    2006.    2007.    ... 2018.    2019.    2020.   ]
 [ 272.311  257.122  271.411 ...  282.722  226.5    255.023]
 [ 270.278  244.211  270.    ...  255.023  255.023  254.056]
 ...
 [ 258.789  265.1    260.278 ...  253.601  260.444  252.911]
 [ 262.9    251.111  259.822 ...  212.111  253.601  253.601]
 [ 260.444  261.889  244.    ...  253.601  252.511  278.1  ]]
